PSalud/Controllers/AffiliatesController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using PSalud.DataAccess.NHibernate;
using PSalud.DataAccess.Repositories;
using PSalud.Entities.Domains.Generals;
using PSalud.Entities.Domains.Pacientes;
using PSalud.Entities.Domains.Profiles;
using PSalud.Models.Affiliates;

namespace PSalud.Controllers
{
    public class AffiliatesController : Controller
    {
        protected static UnitOfWork UoW;
        private static Repository Repository()
        {
            UoW = new UnitOfWork(new NHibernateHelper(ConfigurationManager.ConnectionStrings["PSaludConnectionString"].ConnectionString).SessionFactory);
            var repository = new Repository(UoW.Session);
            return repository;
        }

        public ActionResult NewAffiliate()
        {
            var modelo = new AffiliatesModel();
            modelo.Ciudad = Repository().Query<Ciudades>().ToList();
            modelo.TipoPaciente = Repository().Query<TipoPacientes>().ToList();
            

            return PartialView(new AffiliatesModel());
        }
        
        [HttpPost]
        public ActionResult NewAffiliate(AffiliatesModel model)
        {
            var repo = Repository();
            var newCiudad = repo.First<Ciudades>(x => x.Id_Ciudad == 1);
            var newTipoPaciente = repo.First<TipoPacientes>(x => x.Id_TipoPaciente == 1);
            var newPerson = Mapper.Map<AffiliatesModel, Personas>(model);
            newPerson.Id_Ciudad = newCiudad;
            repo.Add(newPerson);
            var afiliado = Mapper.Map<AffiliatesModel, Pacientes>(model);
            afiliado.AddPerson(newPerson);
            afiliado.AddTipoPaciente(newTipoPaciente);
            repo.Add(afiliado);
            UoW.Commit();
            return RedirectToAction("Index","Home");
        }

        public void GetCiudades()
        {
        }
    }
}

PSalud/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PSalud.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

PSalud/Controllers/MedicsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using PSalud.DataAccess.NHibernate;
using PSalud.DataAccess.Repositories;
using PSalud.Entities.Domains.Clinicas;
using PSalud.Entities.Domains.Generals;
using PSalud.Entities.Domains.Medicos;
using PSalud.Entities.Domains.Pacientes;
using PSalud.Entities.Domains.Profiles;
using PSalud.Models.Medics;

namespace PSalud.Controllers
{
    public class MedicsController : Controller
    {
        protected static UnitOfWork UoW;
        private static Repository Repository()
        {
            UoW = new UnitOfWork(new NHibernateHelper(ConfigurationManager.ConnectionStrings["PSaludConnectionString"].ConnectionString).SessionFactory);
            var repository = new Repository(UoW.Session);
            return repository;
        }

        public ActionResult NewMedic()
        {
            var modelo = new MedicsModel();
            modelo.Ciudad= Repository().Query<Ciudades>().ToList();
            modelo.Especialidades = Repository().Query<Especialidades>().ToList();
            modelo.Clinicas = Repository().Query<Clinicas>().ToList();
           return PartialView(modelo);
        }

        [HttpPost]
        public ActionResult NewMedic(MedicsModel model)
        {
            var repo = Repository();
            var newCiudad = repo.First<Ciudades>(x => x.Id_Ciudad == 1);
            var newTipoPaciente = repo.First<TipoPacientes>(x => x.Id_TipoPaciente == 1);

            var newPerson = Mapper.Map<MedicsModel, Personas>(model);
            newPerson.Id_Ciudad = newCiudad;
            //Save person object
            repo.Add(newPerson);

            var newEspecialidad = repo.First<Especialidades>(x => x.Id_Especialidad == 1);
            var newClinica = repo.First<Clinicas>(x => x.Id_Clinica == 1);

            var newMedic = new Medicos
            {
                Id_Especialidad =  newEspecialidad,
                Id_Clinica = newClinica,
                Id_Persona = newPerson
            };
            repo.Add(newMedic);
            UoW.Commit();
            return RedirectToAction("Index", "Home");
        }
    }
}

PSalud/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
    
}


<div class="row">

   
    <div style="margin-bottom: 2%;">
        <ul class="nav nav-tabs affix" data-spy="affix" data-offset-top="190">
            <li class="active" id="li-afiliados"><a>Afiliados</a></li>
            <li id="li-medicos"><a>Medicos</a></li>
            <li id="li-citas"><a>Citas</a></li>
        </ul>
 </div>  
    <div id="tab-afiliados" class="row">
        <div class="span6">
            @{
                Html.RenderAction("NewAffiliate", "Affiliates");
            } 
             
        </div>
        <div class="span6"> 
            <div class="span6" style="margin-left: 20%;">
                @{
                    //Html.RenderAction("ManageNews", "Administrator");
                }
                
            </div>
            
        </div>
        

        
    </div>
    <div id="tab-medicos" hidden>
        @{
            Html.RenderAction("NewMedic","Medics");
        }  
        
    </div>
    <div id="tab-citas" hidden>
        @{
            //Html.RenderAction("Randomizer", "Administrator");
        }  
    </div>
</div>

<script src="http://code.jquery.com/jquery-1.10.1.min.js"> </script>
<script type="text/javascript">

   
   
    $("li").click(function () {
        $("li").removeClass("active");
        this.className = "active";
    });
    $("#li-afiliados").click(function () {
        $("div[id^= 'tab'").hide();
        $("#tab-afiliados").fadeIn();
    });
    $("#li-medicos").click(function () {
        $("div[id^= 'tab'").hide();
        $("#tab-medicos").fadeIn();
    });
    $("#li-citas").click(function () {
        $("div[id^= 'tab'").hide();
        $("#tab-citas").fadeIn();
    });
   
</script>